// FAKE DATA
export const champs = [
  {
    id: 1,
    title: "Jinx, the Loose Cannon",
    url: "https://i.ibb.co/6D2fsD2/champ-1.jpg",
    originalPrice: 4800,
    salePrice: 2880,
    rating: 5,
  },
  {
    id: 2,
    title: "Vi, the Piltover Enforcer",
    url: "https://i.ibb.co/6WmC3Y0/champ-2.jpg",
    originalPrice: 4800,
    salePrice: 2880,
    rating: 5,
  },
  {
    id: 3,
    title: "Jayce, the Defender of Tomorrow",
    url: "https://i.ibb.co/p450j1q/champ-3.jpg",
    originalPrice: 4800,
    salePrice: null,
    rating: 5,
  },
  {
    id: 4,
    title: "Caitlyn, the Sheriff of Piltover",
    url: "https://i.ibb.co/FH607qm/champ-4.jpg",
    originalPrice: 4800,
    salePrice: 2880,
    rating: 5,
  },
  {
    id: 5,
    title: "Ekko, the Boy Who Shattered Time",
    url: "https://i.ibb.co/tpD6SVj/champ-5.jpg",
    originalPrice: 4800,
    salePrice: 2880,
    rating: 5,
  },
  {
    id: 6,
    title: "Singed, the Mad Chemist",
    url: "https://i.ibb.co/7294Lrk/champ-6.jpg",
    originalPrice: 450,
    salePrice: null,
    rating: 4,
  },
  {
    id: 7,
    title: "Heimerdinger, the Revered Inventor",
    url: "https://i.ibb.co/VS50MBh/champ-7.jpg",
    originalPrice: 3150,
    salePrice: 1890,
    rating: 4.5,
  },
  {
    id: 8,
    title: "Viktor, the Machine Herald",
    url: "https://i.ibb.co/nDNRWCS/champ-8.jpg",
    originalPrice: 4800,
    salePrice: 2880,
    rating: 4.5,
  },
  {
    id: 9,
    title: "Ahri, the Nine-Tailed Fox",
    url: "https://i.ibb.co/XSWMmMY/champ-9.jpg",
    originalPrice: 3150,
    salePrice: 1890,
    rating: 4.5,
  },
  {
    id: 10,
    title: "Zoe, the Aspect of Twilight",
    url: "https://i.ibb.co/PgS47R9/champ-10.jpg",
    originalPrice: 6300,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 11,
    title: "Tristana, the Yordle Gunner",
    url: "https://i.ibb.co/6WBdrbn/champ-11.jpg",
    originalPrice: 1350,
    salePrice: 810,
    rating: 4.5,
  },
  {
    id: 12,
    title: "Nasus, the Curator of the Sands",
    url: "https://i.ibb.co/dLvjZDF/champ-12.jpg",
    originalPrice: 1350,
    salePrice: 810,
    rating: 4.5,
  },
];